# Generated by Django 4.2.16 on 2026-07-09 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tenant',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Devam Ediyor'), ('SUCCESS', 'Başarılı'), ('FAILED', 'Başarısız')], default='PENDING', max_length=10)),
                ('sync_started_at', models.DateTimeField(auto_now_add=True)),
                ('sync_finished_at', models.DateTimeField(blank=True, null=True)),
                ('rows_fetched', models.IntegerField(default=0)),
                ('rows_valid', models.IntegerField(default=0)),
                ('rows_invalid', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='loans.tenant')),
            ],
            options={
                'db_table': 'sync_log',
                'ordering': ['-sync_started_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('RETAIL', 'Bireysel'), ('COMMERCIAL', 'Ticari')], max_length=20)),
                ('loan_account_number', models.CharField(max_length=50)),
                ('customer_id', models.CharField(max_length=50)),
                ('customer_type', models.CharField(max_length=5)),
                ('loan_status_code', models.CharField(max_length=10)),
                ('days_past_due', models.IntegerField(default=0)),
                ('loan_start_date', models.DateField()),
                ('final_maturity_date', models.DateField()),
                ('first_payment_date', models.DateField(blank=True, null=True)),
                ('loan_closing_date', models.DateField(blank=True, null=True)),
                ('total_installment_count', models.IntegerField(default=0)),
                ('outstanding_installment_count', models.IntegerField(default=0)),
                ('paid_installment_count', models.IntegerField(default=0)),
                ('grace_period_months', models.IntegerField(default=0)),
                ('installment_frequency', models.IntegerField(default=1)),
                ('original_loan_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('outstanding_principal_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('nominal_interest_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('kkdf_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('kkdf_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bsmv_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('bsmv_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('internal_rating', models.CharField(blank=True, max_length=20)),
                ('external_rating', models.CharField(blank=True, max_length=20)),
                ('customer_district_code', models.CharField(blank=True, max_length=20)),
                ('customer_province_code', models.CharField(blank=True, max_length=20)),
                ('insurance_included', models.CharField(blank=True, max_length=1)),
                ('loan_product_type', models.CharField(blank=True, max_length=50)),
                ('loan_status_flag', models.CharField(blank=True, max_length=10)),
                ('customer_region_code', models.CharField(blank=True, max_length=20)),
                ('sector_code', models.CharField(blank=True, max_length=20)),
                ('internal_credit_rating', models.CharField(blank=True, max_length=20)),
                ('default_probability', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('risk_class', models.CharField(blank=True, max_length=20)),
                ('customer_segment', models.CharField(blank=True, max_length=50)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='loans.tenant')),
            ],
            options={
                'db_table': 'credit_record',
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('scheduled_payment_date', models.DateField()),
                ('actual_payment_date', models.DateField(blank=True, null=True)),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('principal_component', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_component', models.DecimalField(decimal_places=2, max_digits=18)),
                ('kkdf_component', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bsmv_component', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('installment_status', models.CharField(max_length=5)),
                ('remaining_principal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('remaining_interest', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('remaining_kkdf', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('remaining_bsmv', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='loans.creditrecord')),
            ],
            options={
                'db_table': 'payment_plan',
                'unique_together': {('credit', 'installment_number')},
            },
        ),
        migrations.AddIndex(
            model_name='creditrecord',
            index=models.Index(fields=['tenant', 'loan_type'], name='credit_reco_tenant__87bce4_idx'),
        ),
        migrations.AddIndex(
            model_name='creditrecord',
            index=models.Index(fields=['loan_account_number'], name='credit_reco_loan_ac_a6154b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='creditrecord',
            unique_together={('tenant', 'loan_type', 'loan_account_number')},
        ),
    ]
