# Generated by Django 4.2.16 on 2026-07-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrecord',
            name='customer_type',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='creditrecord',
            name='loan_status_code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='installment_status',
            field=models.CharField(max_length=15),
        ),
    ]
